apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay
  namespace: openshift-operators # or operators
spec:
  channel: unavailable-image-upgrade  # or working-upgrade for successful upgrades
  installPlanApproval: Automatic
  name: quay
  source: alex-operators
  sourceNamespace: openshift-marketplace # or olm
  startingCSV: quay-operator.v3.8.3